name: EAS Build
on:
  pull_request:
    branches:
      - main
      - qa
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: bookquest/package-lock.json
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm
      - name: Install dependencies
        run: npm ci        
      - name: Build on EAS
        run: eas build -p android --profile preview --non-interactive